name: CI — Build C++23 + CUDA 13.0

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up CUDA repository and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get install -y cuda-toolkit-13-0

      - name: Add CUDA to PATH
        run: |
          echo "/usr/local/cuda-13.0/bin" >> $GITHUB_PATH
          echo "/usr/local/cuda-13.0/lib64" >> $GITHUB_PATH

      - name: Verify nvcc and g++
        run: |
          nvcc --version
          g++ --version

      - name: Build with Make
        run: make -j$(nproc)
